name: Automate Video Uploads

on:
#     schedule:
#             - cron: '0 0 * * *'

jobs:
    create-video-snippet:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Setup python
            uses: actions/setup-python@v5
            with:
                python-version: '3.10'

          - name: Install packages
            run:  |
                python -m pip install --upgrade pip
                pip install pytube moviepy
        
          - name: Run script
            run: python create_snippet/create_snippet.py

          - name: Commit changes
            run: |
                git config --global user.name 'AutoUpdate'
                git config --global user.email 'ChimichangaKid@users.noreply.github.com'
                git commit -am "Automated Clip Update"
                git push

